site_name: Приклад довідника

# Repository
repo_name: wpdew-com/git_docs
repo_url: https://github.com/wpdew-com/git_docs
edit_uri: ""

nav:
    - Головна: index.md
    - MD Розмітка: md.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

  features:
    #- toc.integrate
    #- navigation.tabs
    #- navigation.top
    - toc.follow
    - navigation.instant
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: uk
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: cyan
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: indigo
      accent: lime

extra:
  generator: false
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/WpDews
      name: "Чат в Telegram"
    - icon: fontawesome/brands/github
      link: https://github.com/wpdew-com/git_docs
      name: GitHub
    - icon: fontawesome/brands/google
      link: https://wpdew.com
      name: Site

  # Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - mkdocs-video:
      is_video: True
      video_autoplay: False
      video_type: mp4
      css_style:
        width: "100%"
        height: "100%"
  - search:
      lang:
        - uk

#extra:
#  generator: false
 #https://squidfunk.github.io/mkdocs-material/



copyright: |
  &copy; 2024 <a href="https://github.com/wpdew-com/git_docs"  target="_blank" rel="noopener">WpDew</a>